# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.srcs/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo.xci
# IP: The module: 'ddr3_tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.gen/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_tx_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.gen/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.gen/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.srcs/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo.xci
# IP: The module: 'ddr3_tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.gen/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.gen/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Textbook/MicroPhase/Board_cd/A7_Lite/04_source_code/A7_lite_demo_200T/22_hdmi_ddr3_uart/hdmi_ddr3_uart.gen/sources_1/ip/ddr3_tx_fifo/ddr3_tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
