# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.srcs/sources_1/ip/clock_distribution/clock_distribution.xci
# IP: The module: 'clock_distribution' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/clock_distribution/clock_distribution_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_distribution'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/clock_distribution/clock_distribution.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_distribution'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/clock_distribution/clock_distribution_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_distribution'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.srcs/sources_1/ip/clock_distribution/clock_distribution.xci
# IP: The module: 'clock_distribution' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/clock_distribution/clock_distribution_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_distribution'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/clock_distribution/clock_distribution.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_distribution'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/clock_distribution/clock_distribution_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_distribution'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
