# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.srcs/sources_1/ip/ddr3_clock/ddr3_clock.xci
# IP: The module: 'ddr3_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/ddr3_clock/ddr3_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/ddr3_clock/ddr3_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/ddr3_clock/ddr3_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.srcs/sources_1/ip/ddr3_clock/ddr3_clock.xci
# IP: The module: 'ddr3_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/ddr3_clock/ddr3_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/ddr3_clock/ddr3_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Workspace/hdmi_ddr3_fragment_shader_proj/hdmi_ddr3_fragment_shader_proj.gen/sources_1/ip/ddr3_clock/ddr3_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
